service: template-nestjs-and-serverless

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors:
            origin: '*'
      - http:
          method: ANY
          path: '{proxy+}'